export enum PositionEnum {
  GK = "goleiro",
  LB = "Lateral Esquerdo",
  CB = "Zagueiro",
  RB = "Lateral Direito",
  CDM = "Volante",
  CM = "Meio Campo",
  CAM = "Meia Armador",
  LM = "Meia Esquerda",
  RM = "Meia Direita",
  CF = "Segundo Atacante",
  ST = "Atacante",
  RW = "Ponta Direita",
  LW = "Ponta Esquerda",
}
