name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    tags:
    - '*'

jobs:
  build:
    name: build the app
    runs-on: ubuntu-latest

    steps:
      - name: setup ionic and cordova
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Checkout code
        uses: actions/checkout@v2   
      - run: npm ci
      - run: ionic cordova build android

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/work/scout/scout/platforms/android/app/build/outputs/apk/debug/app-debug.apk"
        body: "Scout release"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
